scheme_new scheme_merkle_new;
scheme_get_leaf_rr_list scheme_merkle_get_leaf_rr_list;
scheme_calc_digest scheme_merkle_calc_digest;
scheme_iterate scheme_merkle_iterate;
scheme_free scheme_merkle_free;
