scheme_new scheme_simple_new;
scheme_get_leaf_rr_list scheme_simple_get_leaf_rr_list;
scheme_calc_digest scheme_simple_calc_digest;
scheme_iterate scheme_simple_iterate;
scheme_free scheme_simple_free;
